name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"

categories:
  - title: "Features"
    labels: ["enhancement", "feature"]
  - title: "Fixes"
    labels: ["bug", "fix"]
  - title: "Documentation"
    labels: ["documentation", "docs"]
  - title: "Maintenance"
    labels: ["chore", "refactor", "dependencies"]

change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
exclude-labels: ["skip-changelog"]

version-resolver:
  major:
    labels: ["major"]
  minor:
    labels: ["minor", "enhancement", "feature"]
  patch:
    labels: ["patch", "bug", "fix", "chore", "documentation", "docs", "dependencies"]

template: |
  ## What’s Changed
  $CHANGES
