name: Bug Report
description: Report a bug or issue with the site
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: "Example: The contact form doesn't submit when..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: "Example: The form should submit and show a success message."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: "Example: The form shows a validation error..."
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser(s) are you experiencing the issue in?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: Device Type
      description: What type of device are you using?
      options:
        - Desktop
        - Mobile
        - Tablet
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Console Errors
      description: If applicable, add screenshots or console errors to help explain the problem.
      placeholder: Paste screenshots or error messages here.

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the problem (e.g., viewport size, network conditions, accessibility settings).

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have checked the browser console for error messages
          required: false

  - type: markdown
    attributes:
      value: |
        ---

        ## Implementation Instructions for Contributors

        **IMPORTANT**: When resolving this bug, you must:

        - Comply with Technical Governance:
          - Follow [Engineering Standards](https://github.com/vicenteopaso/vicenteopaso-vibecode/blob/main/docs/ENGINEERING_STANDARDS.md)
          - Follow [Architecture](https://github.com/vicenteopaso/vicenteopaso-vibecode/blob/main/docs/ARCHITECTURE.md) guidelines
          - Follow [Technical Governance](https://vicenteopaso.com/technical-governance) principles
        - Document all changes:
          - Update relevant documentation in `docs/` directory
          - Update component documentation if modifying components
          - Update README.md if behavior changes
        - Ensure all quality checks pass:
          - Run `pnpm lint` and fix all linting errors
          - Run `pnpm typecheck` and fix all type errors
          - Run `pnpm test` and ensure all unit tests pass
          - Run `pnpm test:e2e` and ensure all E2E tests pass
        - Verify the fix:
          - Test in the browsers mentioned in this issue
          - Test on the device types mentioned in this issue
          - Verify no regressions in related functionality
